version: "3.8"

services:
  db:
    image: postgres
    ports: #add line.
      - '5432:5432'
    environment: # add line.
      - POSTGRES_DB=IP_db
      - POSTGRES_USER=IP_user
      - POSTGRES_PASSWORD=IP_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: ip-pgadmin #you can change this
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hookahs@admin.hk
      PGADMIN_DEFAULT_PASSWORD: hookahs_password
    restart: always

  web:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/usr/src/back/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db


volumes:
  postgres_data: